import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
// import { PrismaClient } from "@prisma/client";
import { useUser } from "@clerk/nextjs";
import { Input } from "antd";
// import { api } from "~/utils/api";

const { Search } = Input;

// import { api } from "~/utils/api";

// const prismaClient = new PrismaClient();

const Home: NextPage = () => {
  const userObj = useUser();
  const userData = userObj?.user;
  console.log(userData)
  // const datas = api.todo.getAll.useQuery();
  // console.log("datas ", datas)

  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.pageContainer}>
        <div className={styles.headerCls}>
          <span className={styles.logo}>待办事项</span>
          <img className={styles.avatar} src={userData?.profileImageUrl} />
        </div>
        <div>
          <Search
            placeholder="请输入代办项目"
            enterButton="新&nbsp;&nbsp;增"
            size="large"
          />
        </div>
      </main>
    </>
  );
};

export default Home;
